# Generated by Django 3.1 on 2020-08-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Message',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
